@PaymentSystem.Api_HostAddress = http://localhost:5277

POST {{PaymentSystem.Api_HostAddress}}/api/cards
Content-Type: application/json

{
  "bankAccountId": 1,
  "cardBank": "VakýfBank",
  "dailyLimitMinor": 500000
}