@PaymentSystem.Api_HostAddress = http://localhost:5277

POST {{PaymentSystem.Api_HostAddress}}/api/customers
Content-Type: application/json

{
  "firstName": "Beytullah",
  "lastName": "Atasoy",
  "email": "yanlis-mail"
}